# Generated by Django 5.2 on 2025-05-02 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(help_text='URL interna (p.ej. /app1/) o externa', max_length=255)),
                ('users', models.ManyToManyField(help_text='Usuarios que pueden ver esta app', related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
