# Generated by Django 5.2 on 2025-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.CharField(help_text='Ruta interna (p.ej. /consignaciones-atico/)', max_length=255),
        ),
    ]
